### ISSUE TITLE
Snoop 2.10 crashes when snooping a WPF App that uses AvalonDock

### ISSUE THREAD

**Issue by frankbjr** [cplotts/snoopwpf#100]
I tried to use Snoop with an app I am writing, and it crashes when you try to inspect anything in Snoop's left pane.  Simply hitting the + on the Snooped App in the left pane to expand it will cause a crash.  To rule out whether it was something I had introduced in my code, I went looking for a sample program with AvalonDock which is written by Xceed (The Control vendor).  I downloaded Xceed's Extended WPF Toolkit Live Explorer.  I fired up the live explorer, choose AvalonDock & attempt to Snoop it and the App crashes and the Snoop window goes away.  This is the same behavior with my App & Snoop.  

The link to the Live Explorer Zip can be found on Xceed's git page for the wpftoolkit (along with source) at https://github.com/xceedsoftware/wpftoolkit/releases .

To reproduce the issue:
1)  Go to the above URL.
2) Download Extended.WPF.Toolkit.Live.Explorer.Zip from the Asset section.
3) Unzip it.
4) Run the LiveExplorer.
5) Choose the AvalonDock control in the live explorer app.
6) Attach Snoop to the App
7) Attempt to expand the App node (only node) in the Left pane of Snoop.
8) Live Explorer will terminate and Snoop window will close.

Thanks,
-Frank

**Comment by batzen** [comment]
Will have a look at this as soon as i can.

**Comment by rmadsen-ks** [comment]
I also experience this problem the application I'm working on. It works with Snoop 2.8, but would like to add that it also crashes with Snoop 2.9.

**Comment by frankbjr** [comment]
I tried 2.8 this morning, on my project and it works beautifully.

**Comment by batzen** [comment]
Just tried to reproduce your issue using the version 2.10 of snoop and it works without any problems.
Could you try to update to version 2.10?

**Comment by frankbjr** [comment]
I was using 2.10.  I already installed/uninstalled 2.10 twice thinking maybe it was a botched install.  

Could it be my environment?  Win 10 Pro x64 environment.

With my app, I have tried building it x86 or x64 with same result.

I also noticed that rmadsen-ks is having same issue.
Would you like me to video it?

**Comment by batzen** [comment]
A video doesn't help.
An actual error message + stacktrace would help.
Any chance you could attach a debugger while trying to snoop?

**Comment by frankbjr** [comment]
Absolutely.  Unfortunately my program is way to complicated a setup to post.  That is why I found the LiveExplorer where the same failure was exhibited.  I certainly get needing the stack trace.  Here it is from a session with my app:

When I drop the target on my app, I get the following in the output window:

> Got WM_GOBABYGO message
> acmLocal = C:\Program Files (x86)\Snoop\Snoop.exe$Snoop.SnoopUI$GoBabyGo
> About to load assembly C:\Program Files (x86)\Snoop\Snoop.exe
> About to load type Snoop.SnoopUI
> Just loaded the type Snoop.SnoopUI
> About to invoke GoBabyGo on type Snoop.SnoopUI
> Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
> Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
> Exception thrown: 'System.MissingMethodException' in mscorlib.dll
> Exception thrown: 'System.MissingMethodException' in mscorlib.dll
> Exception thrown: 'System.Security.SecurityException' in mscorlib.dll
> Exception thrown: 'System.Security.SecurityException' in mscorlib.dll
> Exception thrown: 'System.Security.SecurityException' in mscorlib.dll
> Exception thrown: 'System.Security.SecurityException' in mscorlib.dll
> Exception thrown: 'System.IO.FileNotFoundException' in mscorlib.dll
> Return value of GoBabyGo on type Snoop.SnoopUI is True

I know that is the normal expected behavior.

When I try to expand the node in the left pane of snoop, I get:

> Managed Debugging Assistant 'FatalExecutionEngineError' 
> The runtime has encountered a fatal error. The address of the error was at 0x6b873b1f, on thread 0x7780. The error code is 0x80131623. This error may be a bug in the CLR or in the unsafe or non-verifiable portions of user code. Common sources of this bug include user marshaling errors for COM-interop or PInvoke, which may corrupt the stack.
> 

And here is the stack trace:
![image](https://user-images.githubusercontent.com/34729473/48501230-9ce22100-e7f1-11e8-9e9d-4e1efdf6dcdf.png)

Thanks for your effort.

**Comment by batzen** [comment]
Ok. Can reproduce your issue.
Totally missed the step which said to select avalondock.

**Comment by batzen** [comment]
Fixed it in https://github.com/cplotts/snoopwpf/pull/104

**Comment by ryanvs** [comment]
Is there a release for this fix? It looks like 2.10.0 was released before this fix. I don't recall having this issue with 2.8, but I've updated so many assemblies in my project recently that it gets hard to tell what may have caused the issue (Gemini WPF including Caliburn Micro, Xceed, Fody, etc.).

**Comment by batzen** [comment]
There is no release for that fix yet. Will try to get it out during the weekend.
