### ISSUE TITLE
Snoop cannot start

### ISSUE THREAD

**Issue by hillin** [cplotts/snoopwpf#126]
Hi,

Snoop (both 2.09 and 2.10) cannot start on my computer. It worked until several days ago, and the issue seems to be related to a FontFamily problem (could be that I installed some new fonts).

Attaching a debugger to Snoop.exe gives the following exception:

> System.TypeInitializationException: 'The type initializer for 'System.Windows.Media.FontFamily' threw an exception.'

The call stack is attached as Attachment 1. Where at the 7th stack frame:
> PresentationFramework.dll!System.Windows.Controls.TextBlock.MeasureOverride(System.Windows.Size constraint)

I can see the local variable `this` points to a TextBlock whose text is `SNOOP`. It seems the exception was thrown while resolving the font family for this TextBlock.

The stack trace of the exception is attached as Attachment 2. The inner exception was an IOException, whose stack trace is attached as Attachment 3.

#### Attachment 1
Call stack:

> PresentationCore.dll!System.Windows.Media.Typeface.Typeface(System.Windows.Media.FontFamily fontFamily, System.Windows.FontStyle style, System.Windows.FontWeight weight, System.Windows.FontStretch stretch)
 	PresentationFramework.dll!MS.Internal.Text.DynamicPropertyReader.GetTypeface(System.Windows.DependencyObject element)
 	PresentationFramework.dll!MS.Internal.Text.TextProperties.InitCommon(System.Windows.DependencyObject target)
 	PresentationFramework.dll!MS.Internal.Text.TextProperties.TextProperties(System.Windows.FrameworkElement target, bool isTypographyDefaultValue)
 	PresentationFramework.dll!System.Windows.Controls.TextBlock.GetLineProperties()
 	PresentationFramework.dll!System.Windows.Controls.TextBlock.EnsureTextBlockCache()
 	PresentationFramework.dll!System.Windows.Controls.TextBlock.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.Controls.StackPanel.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureCell(int cell, bool forceInfinityV)
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureCellsGroup(int cellsHead, System.Windows.Size referenceSize, bool ignoreDesiredSizeU, bool forceInfinityV)
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!MS.Internal.Helper.MeasureElementWithSingleChild(System.Windows.UIElement element, System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.Controls.ContentPresenter.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.Controls.Grid.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.Controls.Decorator.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.Documents.AdornerDecorator.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.Controls.Border.MeasureOverride(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.Window.MeasureOverrideHelper(System.Windows.Size constraint)
 	PresentationFramework.dll!System.Windows.Window.MeasureOverride(System.Windows.Size availableSize)
 	PresentationFramework.dll!System.Windows.FrameworkElement.MeasureCore(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.UIElement.Measure(System.Windows.Size availableSize)
 	PresentationCore.dll!System.Windows.Interop.HwndSource.SetLayoutSize()
 	PresentationCore.dll!System.Windows.Interop.HwndSource.RootVisualInternal.set(System.Windows.Media.Visual value)
 	PresentationFramework.dll!System.Windows.Window.SetRootVisual()
 	PresentationFramework.dll!System.Windows.Window.SetupInitialState(double requestedTop, double requestedLeft, double requestedWidth, double requestedHeight)
 	PresentationFramework.dll!System.Windows.Window.CreateSourceWindowImpl()
 	PresentationFramework.dll!System.Windows.Window.ShowHelper(object booleanBox)
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, bool isSingleParameter)
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, bool isSingleParameter, System.Delegate catchHandler)
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.InvokeImpl()
 	mscorlib.dll!System.Threading.ExecutionContext.runTryCode(object userData)
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)
 	WindowsBase.dll!System.Windows.Threading.DispatcherOperation.Invoke()
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.ProcessQueue()
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WndProcHook(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o)
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, bool isSingleParameter)
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, bool isSingleParameter, System.Delegate catchHandler)
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.InvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, bool isSingleParameter)
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam)
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.TranslateAndDispatchMessage(ref System.Windows.Interop.MSG msg)
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame frame)
 	PresentationFramework.dll!System.Windows.Application.RunInternal(System.Windows.Window window)
 	Snoop.exe!Snoop.App.Main()

#### Attachment 2

Stack trace of the `TypeInitializeException`:

>    at System.Windows.Media.Typeface..ctor(FontFamily fontFamily, FontStyle style, FontWeight weight, FontStretch stretch)
   at MS.Internal.Text.DynamicPropertyReader.GetTypeface(DependencyObject element)
   at MS.Internal.Text.TextProperties.InitCommon(DependencyObject target)
   at MS.Internal.Text.TextProperties..ctor(FrameworkElement target, Boolean isTypographyDefaultValue)
   at System.Windows.Controls.TextBlock.GetLineProperties()
   at System.Windows.Controls.TextBlock.get_ParagraphProperties()

#### Attachment 3
Stack trace of the inner `IOException`:

>   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.GetValueNames()
   at MS.Internal.FontCache.FontSourceCollection.SetFontSources()
   at MS.Internal.FontCache.FontSourceCollection.GetEnumerator()
   at MS.Internal.FontCache.FamilyCollection.BuildFamilyList(List`1& familyList, SortedDictionary`2& familyNameList, SortedList`2& frequentStrings)
   at MS.Internal.FontCache.FamilyCollection.MS.Internal.FontCache.IFontCacheElement.AddToCache(CheckedPointer newPointer, ElementCacher cacher)
   at MS.Internal.FontCache.HashTable.Lookup(IFontCacheElement e, Boolean add)
   at MS.Internal.FontCache.CacheManager.Lookup(IFontCacheElement e)
   at System.Windows.Media.FontFamily..cctor()

**Comment by hillin** [comment]
Some further investigation shows this is potentially an internal bug of .NET Framework. So I grabbed part of the code from [FontSourceCollection.cs](https://referencesource.microsoft.com/#PresentationCore/Core/CSharp/MS/Internal/FontCache/FontSourceCollection.cs,0589afbc5af4ca27) and wrote the following test code:

    internal class Program
    {
        private const string InstalledWindowsFontsRegistryKey = @"SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts";

        private static void Main(string[] args)
        {
            using (var fontsKey = Registry.LocalMachine.OpenSubKey(InstalledWindowsFontsRegistryKey))
            {
                foreach (var fontValue in fontsKey.GetValueNames())
                {
                    var fileName = fontsKey.GetValue(fontValue) as string;

                    Console.WriteLine(fileName);
                }
            }

            Console.ReadKey();
        }
    }

This code runs without any problem under .NET Framework 4.0+, but throws the same exception if targeted to .NET Framework 3.5.

But isn't Snoop 2.10 already switched to .NET Framework 4.0? Am I missing something?

**Comment by batzen** [comment]
I upgraded snoop to .net 4.0 in october. Snoop 2.10 was released in September so the first version being on .net 4.0 would be 2.11 (which is not yet released).

**Comment by hillin** [comment]
Thanks @batzen !

The problem is due to some fonts installed on my system generated extremely long registry value names, which exceeded the length limit of .NET Framework 3.5 (256 characters). After removing these fonts Snoop is working properly now.
