### ISSUE TITLE
Upgrade .Net framework WPF Snoop is targeting

### ISSUE THREAD

**Issue by srgloureiro** [cplotts/snoopwpf#37]
It does not make any sense to still target .Net Framework 3.5. It should already work over 4.x

**Comment by MaciekRakowski** [comment]
Actually, there is a reason we target a low framework. If we target framework 4.x+, we will have backwards compatibility issues. Here is why:

Snoop actually injects itself into the WPF process. This means that Snoop forces the "Snooped App" to load the Snoop assemblies as though the "Snooped App" actually referenced these assemblies. This trick is done via a series of WinAPI calls (in this case, it makes sense to use Managed C++ as every other call would have to be a P/Invoke call had this part been written in C#):
https://github.com/cplotts/snoopwpf/blob/master/ManagedInjector/Injector.cpp

That being said, it is not possible for a WPF 3.X app to reference 4.5+ assemblies without targeting .NET 4.5.

Therefore, we would need to make some large changes to target purely 4.5+, and possibly maintain 2 versions of Snoop: one that targets 3.5 and one that targets 4.5+, and inject the version of Snoop.exe (applications can reference other .NET exe's as though they were .DLLfiles) depending on the "Snooped App".

Does this explanation make sense as to why we are targeting 3.5? If not, I welcome any counter-argument or reason as to why we should make Snoop reference .NET version 4.X+.

**Comment by volleynerd** [comment]
Yes thanks that makes total sense.  I've looked through that injection code in the past.  It would be a bummer to have to maintain 2 versions of the code just to upgrade to .NET 4+ really for not much benefit.

**Comment by MaciekRakowski** [comment]
Since this is a non-issue, and will actually be counter-productive to the project, I will go ahead and close this issue.
