### ISSUE TITLE
Hang on PriorityBinding

### ISSUE THREAD

**Issue by KGuetter** [cplotts/snoopwpf#42]
With the attached WPF application (VS2013), Snoop hangs when viewing the properties of the TextBock. 

 This seems to be caused by the PriorityBinding; with a normal binding the hang does not occur.

[WpfApplication6.zip](https://github.com/cplotts/snoopwpf/files/86097/WpfApplication6.zip)

**Comment by MaciekRakowski** [comment]
Thank you so much for finding this bug. I actually have created a (hackish) fix by special-casing for PrioirtyBindingExpression. When I get a chance, I will create a branch for you, and you can evaluate it for yourself. The Repo app certainly helped a lot! Thank you!

**Comment by MaciekRakowski** [comment]
Hi,

I fixed this issue in the hang-on-PriorityBinding branch right here: 
https://github.com/cplotts/snoopwpf/tree/hang-on-PriorityBinding

If you can, please evaluate the fix, and let me know if it works. Cory is the owner of this project, and will update the master branch accordingly. A confirmation from you will be greatly appreciated.

Regards,
Maciek

**Comment by KGuetter** [comment]
Hello Maciek,

thank you for the very quick reaction.
And yes, it works.

Regards
Klaus

**Comment by cplotts** [comment]
Wow. This hang on PriorityBinding is nasty. I am going to merge this right away. I can't believe I haven't run into this. We use PriorityBinding(s) here and there in our application.

**Comment by cplotts** [comment]
Thank you for providing us with a repro app. That is always very helpful!

**Comment by cplotts** [comment]
Created pull request [#46](https://github.com/cplotts/snoopwpf/pull/46) for the fix that Maciek created.
