### ISSUE TITLE
Info missing on exact requirements to open and build the tree

### ISSUE THREAD

**Issue by zb-z** [cplotts/snoopwpf#58]
Should be in README.md. In particular about WIX - what exactly (is "WiX Toolset build tools" enough or do you need "WiX Toolset Visual Studio Extension" as well) , URL-s for pages where to find it/them (http://wixtoolset.org/releases/v3.11/stable, but that's still not the final path). 

Also for importing targets as dependencies it would be good to add conditions like Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\WiX\v3.x\Wix.targets')" which should prevent throwing error so that the project could load, never mind that it won't be buildable. The guy opening it will see files etc.

If it's available as a nuget package that would be an option worth considering since VS knows how to auto load packages that are dependencies, if asked nicely :-) (meaning without one nasty tag to throw error on purpose).

Oh and a warning to people not to succumb to the VS pressure to "migrate to the latest version" project which are clearly clearly marked as being CLR version specific (-3.5 and -4.0 for launcher and injector). Don't know if there's a tag to prevent that as well - VS is very much version-gready and persuasive :-)

**Comment by cplotts** [comment]
I have updated the README.md file and have included a whole new section on how to build Snoop and how to work with it ... in particular, just pointing out the SnoopOnly.sln solution.

Thanks for bringing this issue up!
