### ISSUE TITLE
Virus / Trojan?

### ISSUE THREAD

**Issue by OkumaScott** [cplotts/snoopwpf#65]
The Setup.exe binary appears to be infected with some kind of virus.
> snoopwpf-2.8.0\SnoopInstaller\bin\Release\Setup.exe

When run, it attempts to go out to 192.195.77.40 and download additional files. 

Looking at the WiX installer source, I don't think it should be doing this.

**Comment by cplotts** [comment]
I don't think it is a virus. Setup.exe contains the stuff which also installs the VC++ redists ... it's probably that.

**Comment by OkumaScott** [comment]
I highly doubt it seeing as how my machine has all possible VC++ redists already installed.
Also the IP seems suspicious.

**Comment by cplotts** [comment]
So ... I finally got around to doing a binary compare of the Setup.exe file that was originally committed on 10/4/2012 ... to what is currently in the download that I'm making available via cplotts.com.

They are binary equal ... so I think everything must be legit. I don't know why it is going out to 192.195.77.40 ... again, I assume that it is trying to download the redists.

I also looked up the specifics of this commit ... and again, it's sole purpose is to install the MSVC++ redists for x86 and x64.
https://github.com/cplotts/snoopwpf/commit/b89f630e820bc7075dba667cf77cc6601ce2c9de#diff-bd0262902045880c53891734ee69e521

You do not have to use the Setup.exe at all ... if you have the redists already installed (as you said you did) ... you can simply run Setup.msi.

You can always manually install the redists too.
x86 Redist -- [http://www.microsoft.com/downloads/en/details.aspx?FamilyID=a7b7a05e-6de6-4d3a-a423-37bf0912db84](url)
x64 Redist -- [http://www.microsoft.com/downloads/en/details.aspx?FamilyID=BD512D9E-43C8-4655-81BF-9350143D5867](url)

Finally, you can always simply build the source code yourself.

**Comment by cplotts** [comment]
The WiX installer source is responsible only for creating Snoop.msi. Setup.exe was created separately and checked in as a binary.

**Comment by cplotts** [comment]
Another thought ... maybe Setup.exe doesn't check to see if the redists are installed before trying to download them. I honestly don't know much about Setup.exe other than what I've told you ... Jason Jibben, another Snoop collaborator, did that part for me.

**Comment by cplotts** [comment]
And sorry for not being able to comment in-depth till now. I don't have much time for Snoop anymore ... but I did want to make sure that I wasn't spreading malware or a virus around! :+1:
