### ISSUE TITLE
Add release binaries to GitHub

### ISSUE THREAD

**Issue by gtaylor1981** [cplotts/snoopwpf#74]
Please add the Snoop binaries here on GitHub.
(I didn't spot the link to the blog download at first, and the CodePlex link appears to be blocked by Chrome.)
Thanks!

**Comment by cplotts** [comment]
I'm going to merge some pull requests, put together a release, and then make the binaries available here instead of my blog. I thought at one point that GitHub didn't allow that ... but I know now that it does.

**Comment by cplotts** [comment]
Release binaries are now attached to the release.
https://github.com/cplotts/snoopwpf/releases/tag/2.9.0
