### ISSUE TITLE
Snoop not detecting anything when application hosted in browser. Attached the screenshot.

### ISSUE THREAD

**Issue by mahimabhowmik** [cplotts/snoopwpf#78]
Environment : IE11, Windows 2010.
![snooping](https://user-images.githubusercontent.com/42257213/43939830-cc3749b8-9caf-11e8-80cc-d1b07ef46b16.PNG)

**Comment by batzen** [comment]
Did it work with snoop version 2.8? If yes then the only workaround is to downgrade till i fixed this issue.

**Comment by cplotts** [comment]
I deleted the comments on the other thread. Having this new issue is the right way to go.

**Comment by cplotts** [comment]
I am curious, however, did Snoop 2.8.0 work for you before?

**Comment by cplotts** [comment]
If you need to go back to Snoop 2.8.0 ... I just uploaded binaries to https://github.com/cplotts/snoopwpf/releases/tag/2.8.0.

**Comment by mahimabhowmik** [comment]
My bad... I used snoop on the standalone desktop apps and not the browser hosted. Expected it to work in the same way in browser as well. Sorry for inconvenience.
