### ISSUE TITLE
Fatal ExecutionEngineException when process has hidden windows without composition target

### ISSUE THREAD

**Issue by gix** [cplotts/snoopwpf#86]
Commit 2a5da54671990381 changed the navigation tree to include all windows of the process. This may include windows that have been created but not yet shown. Such windows do not have a composition target yet and cannot be layouted. But using them as source of a VisualBrush will forcibly layout them and trigger WPF-internal asserts that crash the process (the managed debugger displays a fatal exception indicating process corruption which is not the case here).

Simple repro: Create a new empty WPF project and add this to the MainWindow:

    public partial class MainWindow
    {
        private Window window = new Window {
            Visibility = Visibility.Hidden // Must be hidden (not collapsed) to not skip layouting.
        };

        public MainWindow()
        {
            InitializeComponent();
        }
    }

**Comment by cplotts** [comment]
Thank you @gix. This has been merged into Snoop master.

**Comment by cplotts** [comment]
Hey, by the way @gix ... I love your https://github.com/gix/PresentationTheme.Aero project. Would love to toy with that sometime.
