### ISSUE TITLE
[Question] .NET Framework 3.5 in snoop 2.10

### ISSUE THREAD

**Issue by Crypt32** [cplotts/snoopwpf#95]
In release notes you said that snooping WPF 3.5 application is deprecated. However, snoop itself requires .NET 3.5. Is it intentional? At the moment I don't have apps that require .NET 3.5 and when launched Snoop 2.10 it asked for .NET 3.5

**Comment by cplotts** [comment]
Yeah, I think we have an issue here ... I haven't had a chance to look into it quite yet ... but will be doing so soon. Stay tuned.

**Comment by batzen** [comment]
As far as i remember i fixed this in one of my PRs.

**Comment by cplotts** [comment]
I just merged @batzen's pull requests. I'm closing for now. If you still see this as an issue, let us know, and I'll re-open.

**Comment by itsho** [comment]
I guess that it's #102 - no release is containing this commit yet.
