### ISSUE TITLE
Conditional ref to Automation dll

### ISSUE THREAD

**Issue by cskwrd** [cplotts/snoopwpf#97]
What is the purpose of conditionally including this reference?

https://github.com/cplotts/snoopwpf/blob/247be138067c33416cb41dcc5438c55846dea5b8/Snoop/Snoop.csproj#L363

When I try to build Snoop.sln it fails because the assembly I have on my machine is targeted to v4.5. If I remove the conditional ref so the package ref is included, the solution builds fine.

I have been building the Release version, btw.

**Comment by batzen** [comment]
It's done by paket.
If you want to retarget to .net 4.5 you'd have to call "paket install" in the root folder of the cloned repo.
